### ISSUE TITLE
End Credits fail to display (blank window)

### ISSUE THREAD

**Issue by klugemonkey** [SpigotMC/SpigotCraft#104]
Jumping into the portal in the end that is created by killing the Ender Dragon should roll the credits, however only a blank, black window is displayed.

Exception in thread "Thread-8" java.lang.NullPointerException
    at paulscode.sound.codecs.CodecJOrbis.initialize(CodecJOrbis.java:295)
    at paulscode.sound.libraries.SourceLWJGLOpenAL.preLoad(SourceLWJGLOpenAL.java:687)
    at paulscode.sound.Source.stream(Source.java:928)
    at paulscode.sound.StreamThread.run(StreamThread.java:129)

Logging out of the client and logging back in returns to the same blank window.   But the sound is at least now playing for the end credits.

[20:16:48] [Client thread/INFO]: [CHAT] partyfowl joined the game
[20:16:48] [Client thread/INFO]: [CHAT] Welcome to SpigotCraft!
[20:16:48] [Client thread/INFO]: [CHAT] We currently have 4 community members online.
[20:16:50] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:16:50] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:16:50] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:16:50] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:16:52] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:16:52] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:16:52] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:16:52] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:16:52] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:16:52] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:16:52] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:16:52] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:16:55] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:16:55] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:16:55] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:16:55] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:16:56] [Thread-7/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[20:16:56] [Thread-7/ERROR]: Source 'b0ef1212-74c3-458f-92ff-c15df0f38e53' not found in method 'play'
[20:16:57] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:16:57] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:16:57] [Thread-7/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:16:57] [Thread-7/ERROR]: Invalid enumerated parameter value.
[20:16:58] [Thread-7/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[20:16:58] [Thread-7/ERROR]: Source '927c2f92-947c-4aef-b014-6ae234134a1f' not found in method 'play'
[20:16:58] [Thread-7/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[20:16:58] [Thread-7/ERROR]: Source 'af66c3bc-8340-44b6-ae84-73380efce7da' not found in method 'play'
[20:17:00] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:17:00] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:17:01] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:17:01] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:17:01] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:17:01] [Thread-8/ERROR]: Invalid enumerated parameter value.
[20:17:01] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:17:01] [Thread-8/ERROR]: Invalid enumerated parameter value.
Exception in thread "Thread-7" java.lang.NullPointerException
    at com.jcraft.jorbis.Info.clear(Info.java:114)
    at paulscode.sound.codecs.CodecJOrbis.cleanup(CodecJOrbis.java:407)
    at paulscode.sound.Source.cleanup(Source.java:363)
    at paulscode.sound.libraries.SourceLWJGLOpenAL.cleanup(SourceLWJGLOpenAL.java:208)
    at paulscode.sound.Library.removeSource(Library.java:1086)
    at paulscode.sound.SoundSystem.CommandRemoveSource(SoundSystem.java:2185)
    at paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2538)
    at paulscode.sound.CommandThread.run(CommandThread.java:121)

**Comment by klugemonkey** [comment]
Esc on the window twice seems to return back to the game.

**Comment by klugemonkey** [comment]
but the weird end credits music is still playing.

**Comment by klugemonkey** [comment]
I rebooted and was able to reproduce the issue.  

20:27:54] [Thread-5/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[20:27:54] [Thread-5/ERROR]: Source 'a723ff82-d6dc-47ff-b5f0-9e7257ff51ed' not found in method 'play'
[20:27:55] [Thread-6/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[20:27:55] [Thread-6/ERROR]: Invalid enumerated parameter value.
Exception in thread "Thread-6" java.lang.NullPointerException
    at paulscode.sound.codecs.CodecJOrbis.initialize(CodecJOrbis.java:295)
    at paulscode.sound.libraries.SourceLWJGLOpenAL.preLoad(SourceLWJGLOpenAL.java:687)
    at paulscode.sound.Source.stream(Source.java:928)
    at paulscode.sound.StreamThread.run(StreamThread.java:129)

**Comment by klugemonkey** [comment]
I tested with 16w04a vanilla single player.  Vanilla works properly.

**Comment by md-5** [comment]
Does not work in Vanilla multiplayer.

**Comment by klugemonkey** [comment]
Still does not work in 16w06a on Spigot version.
Still DOES work on 16w06a on Vanilla Single Player version

[05:46:51] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:46:51] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:46:52] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:46:52] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:01] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:01] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:01] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:01] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:02] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:02] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:03] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:03] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:03] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:03] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:05] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:05] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:05] [Thread-7/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[05:47:05] [Thread-7/ERROR]: Source 'fcb4ed3b-1b47-4264-9d10-734a2bd79d2b' not found in method 'play'
[05:47:08] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:08] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:08] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:08] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:08] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:08] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:08] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:08] [Thread-8/ERROR]: Error unqueuing stream buffers in method 'preLoadBuffers'
[05:47:09] [Thread-7/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[05:47:09] [Thread-7/ERROR]: Source '36cd1a80-6e33-40fa-a39d-43cbeccaee4d' not found in method 'play'
[05:47:10] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:10] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:10] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:10] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:10] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:10] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:11] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:11] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:11] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:11] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:11] [Thread-7/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[05:47:11] [Thread-7/ERROR]: Source 'a89640a3-35d7-4f80-86f5-af4b4da15278' not found in method 'play'
[05:47:11] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:11] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:11] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:11] [Thread-8/ERROR]: Invalid enumerated parameter value.
[05:47:11] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:11] [Thread-8/ERROR]: Error unqueuing stream buffers in method 'preLoadBuffers'
[05:47:12] [Thread-8/ERROR]: Error in class 'ChannelLWJGL OpenAL'
[05:47:12] [Thread-8/ERROR]: Invalid enumerated parameter value.
Exception in thread "Thread-8" java.lang.NullPointerException
    at paulscode.sound.codecs.CodecJOrbis.initialize(CodecJOrbis.java:295)
    at paulscode.sound.libraries.SourceLWJGLOpenAL.preLoad(SourceLWJGLOpenAL.java:687)
    at paulscode.sound.Source.stream(Source.java:928)
    at paulscode.sound.StreamThread.run(StreamThread.java:129)
[05:47:14] [Thread-7/ERROR]: Error in class 'LibraryLWJGLOpenAL'
[05:47:14] [Thread-7/ERROR]: Source 'b9bce4d7-7d6a-4d76-90c4-dfcbee642484' not found in method 'play'

**Comment by md-5** [comment]
Please read:

> Does not work in Vanilla multiplayer.

Not our bug
