### ISSUE TITLE
Skeleton Stray crashed the server

### ISSUE THREAD

**Issue by cindyker** [SpigotMC/SpigotCraft#147]
[01:51:42] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:801) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:675) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: net.minecraft.server.EntitySkeletonStray cannot be cast to net.minecraft.server.EntitySkeleton
        at org.bukkit.craftbukkit.entity.CraftEntity.getEntity(CraftEntity.java:94) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.Entity.getBukkitEntity(Entity.java:55) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:276) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.World.addEntity(World.java:1037) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.WorldServer.addEntity(WorldServer.java:1082) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.SpawnerCreature.a(SpawnerCreature.java:188) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.WorldServer.doTick(WorldServer.java:228) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:790) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        ... 4 more
[01:51:42] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.ClassCastException: net.minecraft.server.EntitySkeletonStray cannot be cast to net.minecraft.server.EntitySkeleton
        at org.bukkit.craftbukkit.entity.CraftEntity.getEntity(CraftEntity.java:94) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.Entity.getBukkitEntity(Entity.java:55) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:276) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.World.addEntity(World.java:1037) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.WorldServer.addEntity(WorldServer.java:1082) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.SpawnerCreature.a(SpawnerCreature.java:188) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.WorldServer.doTick(WorldServer.java:228) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:790) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:675) ~[spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11-R0.1-SNAPSHOT-a1.jar:git-Spigot-b8d0359-cd32091]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[01:51:42] [Server thread/ERROR]: This crash report has been saved to: /root/server/./crash-reports/crash-2016-11-15_01.51.42-server.txt

**Comment by cindyker** [comment]
CrashReport:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 11/15/16 1:51 AM
Description: Exception ticking world

java.lang.ClassCastException: net.minecraft.server.EntitySkeletonStray cannot be cast to net.minecraft.server.EntitySkeleton
        at org.bukkit.craftbukkit.entity.CraftEntity.getEntity(CraftEntity.java:94)
        at net.minecraft.server.Entity.getBukkitEntity(Entity.java:55)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:276)
        at net.minecraft.server.World.addEntity(World.java:1037)
        at net.minecraft.server.WorldServer.addEntity(WorldServer.java:1082)
        at net.minecraft.server.SpawnerCreature.a(SpawnerCreature.java:188)
        at net.minecraft.server.WorldServer.doTick(WorldServer.java:228)
        at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:790)
        at net.minecraft.server.DedicatedServer.D(DedicatedServer.java:399)
        at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:675)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:574)
        at java.lang.Thread.run(Thread.java:745)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
        at org.bukkit.craftbukkit.entity.CraftEntity.getEntity(CraftEntity.java:94)
        at net.minecraft.server.Entity.getBukkitEntity(Entity.java:55)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:276)
        at net.minecraft.server.World.addEntity(World.java:1037)
        at net.minecraft.server.WorldServer.addEntity(WorldServer.java:1082)
        at net.minecraft.server.SpawnerCreature.a(SpawnerCreature.java:188)
        at net.minecraft.server.WorldServer.doTick(WorldServer.java:228)

-- Affected level --
Details:
        Level name: world
        All players: 2 total; [EntityPlayer['cindy_k'/819, l='world', x=4157.49, y=86.27, z=-1625.20](cindy_k at 4157.493679760741,86.27173018723622,-1625.2025007346404), EntityPlayer['Wun'/682, l='world', x=5493.28, y=87.85, z=-725.18](Wun at 5493.281619757916,87.84740106610393,-725.1808439341922)]
        Chunk stats: ServerChunkCache: 1164 Drop: 0
        Level seed: -4224662173976757860
        Level generator: ID 00 - default, ver 1. Features enabled: true
        Level generator options:
        Level spawn location: World: (-175,57,253), Chunk: (at 1,3,13 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Level time: 52102 game time, 61209 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 5936 (now: true), thunder time: 117461 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
