### ISSUE TITLE
Assigning Mutable BlockPos to Shulker

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#159]
```
[09:53:49 WARN]: Tried to assign a mutable BlockPos to a block entity...
java.lang.Error: class net.minecraft.server.BlockPosition$PooledBlockPosition
        at net.minecraft.server.TileEntity.setPosition(TileEntity.java:216) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.Chunk.a(Chunk.java:715) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.World.setTileEntity(World.java:2016) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.Chunk.a(Chunk.java:693) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.World.getTileEntity(World.java:1965) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.WorldServer.getTileEntity(WorldServer.java:127) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.BlockShulkerBox.b(SourceFile:238) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.BlockStateList$BlockData.d(SourceFile:393) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.Block.a(Block.java:278) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.BlockStateList$BlockData.c(SourceFile:383) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.Block.a(Block.java:261) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.BlockStateList$BlockData.a(SourceFile:388) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.World.getCubes(World.java:1209) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.Entity.move(Entity.java:556) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.EntityLiving.g(EntityLiving.java:1748) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.EntityHuman.g(EntityHuman.java:1435) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.EntityLiving.n(EntityLiving.java:2050) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.EntityHuman.n(EntityHuman.java:349) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.EntityLiving.A_(EntityLiving.java:1879) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.EntityHuman.A_(EntityHuman.java:142) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.EntityPlayer.playerTick(EntityPlayer.java:242) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.PlayerConnection.F_(PlayerConnection.java:137) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.NetworkManager.a(NetworkManager.java:233) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.ServerConnection.c(ServerConnection.java:140) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.MinecraftServer.D(MinecraftServer.java:834) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11-R0.1-SNAPSHOT.jar:git-Spigot-edba02f-f3276d3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by md-5** [comment]
Appears to most likely be a Vanilla issue
