### ISSUE TITLE
Using reload throws threaddump and shuts server down

### ISSUE THREAD

**Issue by smmmadden** [SpigotMC/SpigotCraft#224]
[08:23:31 ERROR]: The server has stopped responding!
[08:23:31 ERROR]: Please report this to http://www.spigotmc.org/
[08:23:31 ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[08:23:31 ERROR]: Spigot version: git-Spigot-31fef09-c3d951d (MC: 1.11)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Server thread dump (Look for plugins here before reporting to Spigot!):
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Server thread
[08:23:31 ERROR]:       PID: 18 | Suspended: false | Native: false | State: RUNNABLE
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               com.gamingmesh.jobs.config.ExploreManager.ChunkRespond(ExploreManager.java:69)
[08:23:31 ERROR]:               com.gamingmesh.jobs.dao.JobsDAO.loadExplore(JobsDAO.java:1285)
[08:23:31 ERROR]:               com.gamingmesh.jobs.config.ExploreManager.setExploreEnabled(ExploreManager.java:38)
[08:23:31 ERROR]:               com.gamingmesh.jobs.config.ConfigManager.loadJobSettings(ConfigManager.java:558)
[08:23:31 ERROR]:               com.gamingmesh.jobs.config.ConfigManager.reload(ConfigManager.java:63)
[08:23:31 ERROR]:               com.gamingmesh.jobs.Jobs.reload(Jobs.java:524)
[08:23:31 ERROR]:               com.gamingmesh.jobs.Jobs.startup(Jobs.java:462)
[08:23:31 ERROR]:               com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:710)
[08:23:31 ERROR]:               org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[08:23:31 ERROR]:               org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[08:23:31 ERROR]:               sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:23:31 ERROR]:               sun.nio.ch.SelectorImpl.select(Unknown Source)
[08:23:31 ERROR]:               io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
[08:23:31 ERROR]:               io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
[08:23:31 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[08:23:31 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Netty Server IO #1
[08:23:31 ERROR]:       PID: 29 | Suspended: false | Native: true | State: RUNNABLE
[08:23:31 ERROR]:       Thread is waiting on monitor(s):
[08:23:31 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:23:31 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:23:31 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
[08:23:31 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
[08:23:31 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
[08:23:31 ERROR]:               sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
[08:23:31 ERROR]:               sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:23:31 ERROR]:               sun.nio.ch.SelectorImpl.select(Unknown Source)
[08:23:31 ERROR]:               io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
[08:23:31 ERROR]:               io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
[08:23:31 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[08:23:31 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: File IO Thread
[08:23:31 ERROR]:       PID: 72 | Suspended: false | Native: false | State: TIMED_WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Thread.sleep(Native Method)
[08:23:31 ERROR]:               net.minecraft.server.v1_11_R1.FileIOThread.c(SourceFile:51)
[08:23:31 ERROR]:               net.minecraft.server.v1_11_R1.FileIOThread.run(SourceFile:30)
[08:23:31 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Thread-21
[08:23:31 ERROR]:       PID: 52 | Suspended: false | Native: false | State: WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Object.wait(Native Method)
[08:23:31 ERROR]:               java.lang.Thread.join(Unknown Source)
[08:23:31 ERROR]:               java.lang.Thread.join(Unknown Source)
[08:23:31 ERROR]:               com.Acrobot.ChestShop.Updater.Updater.waitForThread(Updater.java:289)
[08:23:31 ERROR]:               com.Acrobot.ChestShop.Updater.Updater.getLatestType(Updater.java:241)
[08:23:31 ERROR]:               com.Acrobot.ChestShop.Updater.Updater.shouldUpdate(Updater.java:508)
[08:23:31 ERROR]:               com.Acrobot.ChestShop.Updater.Updater.versionCheck(Updater.java:466)
[08:23:31 ERROR]:               com.Acrobot.ChestShop.Updater.Updater.access$400(Updater.java:41)
[08:23:31 ERROR]:               com.Acrobot.ChestShop.Updater.Updater$UpdateRunnable.run(Updater.java:586)
[08:23:31 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Timer-0
[08:23:31 ERROR]:       PID: 49 | Suspended: false | Native: false | State: TIMED_WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Object.wait(Native Method)
[08:23:31 ERROR]:               java.util.TimerThread.mainLoop(Unknown Source)
[08:23:31 ERROR]:               java.util.TimerThread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Abandoned connection cleanup thread
[08:23:31 ERROR]:       PID: 35 | Suspended: false | Native: false | State: TIMED_WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Object.wait(Native Method)
[08:23:31 ERROR]:               java.lang.ref.ReferenceQueue.remove(Unknown Source)
[08:23:31 ERROR]:               com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Netty Server IO #0
[08:23:31 ERROR]:       PID: 28 | Suspended: false | Native: true | State: RUNNABLE
[08:23:31 ERROR]:       Thread is waiting on monitor(s):
[08:23:31 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:23:31 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:23:31 ERROR]:               Locked on:sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
[08:23:31 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
[08:23:31 ERROR]:               sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
[08:23:31 ERROR]:               sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
[08:23:31 ERROR]:               sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
[08:23:31 ERROR]:               sun.nio.ch.SelectorImpl.select(Unknown Source)
[08:23:31 ERROR]:               io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
[08:23:31 ERROR]:               io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
[08:23:31 ERROR]:               io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[08:23:31 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Spigot Metrics Thread
[08:23:31 ERROR]:       PID: 27 | Suspended: false | Native: false | State: TIMED_WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Object.wait(Native Method)
[08:23:31 ERROR]:               java.util.TimerThread.mainLoop(Unknown Source)
[08:23:31 ERROR]:               java.util.TimerThread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Spigot Watchdog Thread
[08:23:31 ERROR]:       PID: 26 | Suspended: false | Native: false | State: RUNNABLE
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               sun.management.ThreadImpl.dumpThreads0(Native Method)
[08:23:31 ERROR]:               sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
[08:23:31 ERROR]:               org.spigotmc.WatchdogThread.run(WatchdogThread.java:76)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Java2D Disposer
[08:23:31 ERROR]:       PID: 24 | Suspended: false | Native: false | State: WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Object.wait(Native Method)
[08:23:31 ERROR]:               java.lang.ref.ReferenceQueue.remove(Unknown Source)
[08:23:31 ERROR]:               java.lang.ref.ReferenceQueue.remove(Unknown Source)
[08:23:31 ERROR]:               sun.java2d.Disposer.run(Unknown Source)
[08:23:31 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Server console handler
[08:23:31 ERROR]:       PID: 21 | Suspended: false | Native: true | State: RUNNABLE
[08:23:31 ERROR]:       Thread is waiting on monitor(s):
[08:23:31 ERROR]:               Locked on:org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
[08:23:31 ERROR]:               Locked on:org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261)
[08:23:31 ERROR]:               Locked on:org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198)
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method)
[08:23:31 ERROR]:               org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:761)
[08:23:31 ERROR]:               org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:794)
[08:23:31 ERROR]:               org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:215)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.WindowsTerminal.access$000(WindowsTerminal.java:55)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.WindowsTerminal$1.read(WindowsTerminal.java:157)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2349)
[08:23:31 ERROR]:               net.minecraft.server.v1_11_R1.DedicatedServer$2.run(DedicatedServer.java:84)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Thread-5
[08:23:31 ERROR]:       PID: 22 | Suspended: false | Native: false | State: RUNNABLE
[08:23:31 ERROR]:       Thread is waiting on monitor(s):
[08:23:31 ERROR]:               Locked on:sun.nio.cs.StreamEncoder.flush(Unknown Source)
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               org.fusesource.jansi.internal.Kernel32.GetConsoleScreenBufferInfo(Native Method)
[08:23:31 ERROR]:               org.fusesource.jansi.WindowsAnsiOutputStream.getConsoleInfo(WindowsAnsiOutputStream.java:103)
[08:23:31 ERROR]:               org.fusesource.jansi.WindowsAnsiOutputStream.processEraseLine(WindowsAnsiOutputStream.java:167)
[08:23:31 ERROR]:               org.fusesource.jansi.AnsiOutputStream.processEscapeCommand(AnsiOutputStream.java:253)
[08:23:31 ERROR]:               org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:125)
[08:23:31 ERROR]:               java.io.FilterOutputStream.write(Unknown Source)
[08:23:31 ERROR]:               sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
[08:23:31 ERROR]:               sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
[08:23:31 ERROR]:               sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
[08:23:31 ERROR]:               sun.nio.cs.StreamEncoder.flush(Unknown Source)
[08:23:31 ERROR]:               java.io.OutputStreamWriter.flush(Unknown Source)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.flush(ConsoleReader.java:976)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.v1_11_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:35)
[08:23:31 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: DestroyJavaVM
[08:23:31 ERROR]:       PID: 20 | Suspended: false | Native: false | State: RUNNABLE
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Server thread
[08:23:31 ERROR]:       PID: 18 | Suspended: false | Native: false | State: RUNNABLE
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               com.gamingmesh.jobs.config.ExploreManager.ChunkRespond(ExploreManager.java:69)
[08:23:31 ERROR]:               com.gamingmesh.jobs.dao.JobsDAO.loadExplore(JobsDAO.java:1285)
[08:23:31 ERROR]:               com.gamingmesh.jobs.config.ExploreManager.setExploreEnabled(ExploreManager.java:38)
[08:23:31 ERROR]:               com.gamingmesh.jobs.config.ConfigManager.loadJobSettings(ConfigManager.java:558)
[08:23:31 ERROR]:               com.gamingmesh.jobs.config.ConfigManager.reload(ConfigManager.java:63)
[08:23:31 ERROR]:               com.gamingmesh.jobs.Jobs.reload(Jobs.java:524)
[08:23:31 ERROR]:               com.gamingmesh.jobs.Jobs.startup(Jobs.java:462)
[08:23:31 ERROR]:               com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:710)
[08:23:31 ERROR]:               org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[08:23:31 ERROR]:               org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[08:23:31 ERROR]:               org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:749)
[08:23:31 ERROR]:               org.bukkit.Bukkit.reload(Bukkit.java:540)
[08:23:31 ERROR]:               org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[08:23:31 ERROR]:               org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:635)
[08:23:31 ERROR]:               net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437)
[08:23:31 ERROR]:               net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400)
[08:23:31 ERROR]:               net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[08:23:31 ERROR]:               net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[08:23:31 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Server Infinisleeper
[08:23:31 ERROR]:       PID: 19 | Suspended: false | Native: false | State: TIMED_WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Thread.sleep(Native Method)
[08:23:31 ERROR]:               net.minecraft.server.v1_11_R1.DedicatedServer$1.run(DedicatedServer.java:59)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: NonBlockingInputStreamThread
[08:23:31 ERROR]:       PID: 16 | Suspended: false | Native: false | State: WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Object.wait(Native Method)
[08:23:31 ERROR]:               org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:278)
[08:23:31 ERROR]:               java.lang.Thread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Snooper Timer
[08:23:31 ERROR]:       PID: 14 | Suspended: false | Native: false | State: TIMED_WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Object.wait(Native Method)
[08:23:31 ERROR]:               java.util.TimerThread.mainLoop(Unknown Source)
[08:23:31 ERROR]:               java.util.TimerThread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Attach Listener
[08:23:31 ERROR]:       PID: 6 | Suspended: false | Native: false | State: RUNNABLE
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Signal Dispatcher
[08:23:31 ERROR]:       PID: 5 | Suspended: false | Native: false | State: RUNNABLE
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Finalizer
[08:23:31 ERROR]:       PID: 3 | Suspended: false | Native: false | State: WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Object.wait(Native Method)
[08:23:31 ERROR]:               java.lang.ref.ReferenceQueue.remove(Unknown Source)
[08:23:31 ERROR]:               java.lang.ref.ReferenceQueue.remove(Unknown Source)
[08:23:31 ERROR]:               java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 ERROR]: Current Thread: Reference Handler
[08:23:31 ERROR]:       PID: 2 | Suspended: false | Native: false | State: WAITING
[08:23:31 ERROR]:       Stack:
[08:23:31 ERROR]:               java.lang.Object.wait(Native Method)
[08:23:31 ERROR]:               java.lang.Object.wait(Unknown Source)
[08:23:31 ERROR]:               java.lang.ref.Reference.tryHandlePending(Unknown Source)
[08:23:31 ERROR]:               java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
[08:23:31 ERROR]: ------------------------------
[08:23:31 INFO]: Startup script './start.sh' does not exist! Stopping server.
[08:23:31 INFO]: Stopping server
[08:23:31 INFO]: [Jobs] Disabling Jobs v3.7.1
[08:23:31 ERROR]: Error occurred while disabling Jobs v3.7.1 (Is it up to date?)
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_112]
        at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_112]
        at com.gamingmesh.jobs.dao.JobsDAO.saveExplore(JobsDAO.java:1239) ~[?:?]
        at com.gamingmesh.jobs.Jobs.onDisable(Jobs.java:759) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.jar:git-Spigot-31fef09-c3d951d]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.jar:git-Spigot-31fef09-c3d951d]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.jar:git-Spigot-31fef09-c3d951d]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.11.jar:git-Spigot-31fef09-c3d951d]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:344) [spigot-1.11.jar:git-Spigot-31fef09-c3d951d]
        at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:462) [spigot-1.11.jar:git-Spigot-31fef09-c3d951d]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:121) [spigot-1.11.jar:git-Spigot-31fef09-c3d951d]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) [spigot-1.11.jar:git-Spigot-31fef09-c3d951d]
        at org.spigotmc.WatchdogThread.run(WatchdogThread.java:85) [spigot-1.11.jar:git-Spigot-31fef09-c3d951d]
[08:23:31 INFO]: [ChestShop] Disabling ChestShop v3.8.12
[08:23:31 INFO]: [SelectionVisualizer] Disabling SelectionVisualizer v1.6.4.0
[08:23:31 INFO]: [EssentialsSpawn] Disabling EssentialsSpawn v2.0.1-b439
[08:23:31 INFO]: [EssentialsExtras] Disabling EssentialsExtras v1.6.2
[08:23:31 INFO]: [CraftBook] Disabling CraftBook v3.9-SNAPSHOT
[08:23:31 INFO]: [CraftBook] Saving persistent data to YAML!
[08:23:31 INFO]: [EssentialsAntiBuild] Disabling EssentialsAntiBuild v2.0.1-b439
[08:23:31 INFO]: [EssentialsGeoIP] Disabling EssentialsGeoIP v2.0.1-b439
[08:23:31 INFO]: [EssentialsChat] Disabling EssentialsChat v2.0.1-b439
[08:23:31 INFO]: [EssentialsProtect] Disabling EssentialsProtect v2.0.1-b439
[08:23:31 INFO]: [Residence] Disabling Residence v4.5.12.1
[08:23:31 INFO]: [Residence] Disabled!
[08:23:31 INFO]: [MythicMobs] Disabling MythicMobs v2.5.1
[08:23:31 INFO]: [MythicMobs] Disabling Mythic Mobs...
[08:23:31 INFO]: [MythicMobs] All active settings have been saved.
[08:23:31 INFO]: [MythicMobs] v2.5.1 has been Disabled!
[08:23:31 INFO]: [Fe] Disabling Fe v0.8.3
[08:23:31 INFO]: [Fe] Vault support disabled.
[08:23:31 INFO]: [LWC] Disabling LWC v1.7.3
[08:23:31 INFO]: [LWC] Flushing protection updates (0)
[08:23:31 INFO]: [HeadDatabase] Disabling HeadDatabase v2.3.2
[08:23:31 INFO]: [Essentials] Disabling Essentials v2.0.1-b439
[08:23:31 INFO]: [Vault][Economy] Essentials Economy unhooked.
[08:23:31 INFO]: [Vault] Disabling Vault v1.5.6-b49
[08:23:31 INFO]: [LagMonitor] Disabling LagMonitor v1.11.3
[08:23:31 INFO]: [HorseTpWithMe] Disabling HorseTpWithMe v1.4.11
[08:23:31 INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4
[08:23:31 INFO]: [EditableSign] Disabling EditableSign v2.4.1
[08:23:31 INFO]: [EditableSign] EditableSign version 2.4.1 is Disabled
[08:23:31 INFO]: [ProtocolLib] Disabling ProtocolLib v4.1.0
[08:23:31 INFO]: [WorldBorder] Disabling WorldBorder v1.8.6
[08:23:31 INFO]: [WorldBorder] [CONFIG] Border-checking timed task stopped.
[08:23:31 INFO]: [MythicLib] Disabling MythicLib v0.0.1-SNAPSHOT
[08:23:31 INFO]: [MythicLib] MythicLib has been disabled.
[08:23:31 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.6.0
[08:23:31 INFO]: [OpenInv] Disabling OpenInv v2.3.9-vk-0.1
[08:23:31 INFO]: [TitleMotd] Disabling TitleMotd v2.0
[08:23:31 INFO]: [WorldEdit] Disabling WorldEdit v6.1.5-SNAPSHOT;3635-cd266ad
[08:23:31 INFO]: [dynmap] Disabling dynmap v2.3-1142
[08:23:31 INFO]: [dynmap] Unloaded 11 components.
[08:23:31 INFO]: [dynmap] Stopping map renderer...
[08:23:37 INFO]: [dynmap] Disabled
[08:23:37 INFO]: Saving players
[08:23:37 INFO]: smmmadden lost connection: Server closed
[08:23:37 INFO]: smmmadden left the game
[08:23:37 INFO]: Saving worlds
[08:23:37 INFO]: Saving chunks for level 'world'/Overworld
[08:23:37 INFO]: Saving chunks for level 'world_nether'/Nether
[08:23:37 INFO]: Saving chunks for level 'world_the_end'/The End
>Press any key to continue . . .

**Comment by MiniDigger** [comment]
seems like Jobs has problems handling the reload. don't reload or contact the author. nothing related to spigot.
