### ISSUE TITLE
Used items don't combine in crafting table or user inventory

### ISSUE THREAD

**Issue by klugemonkey** [SpigotMC/SpigotCraft#301]
Trying to combine two used items such as bows or armor does not behave correctly and returns the source items after any change in the slots are made after the user moves the output slot to the inventory.  This was observed with bows and armor (helmet).  Works correctly in vanilla single-player.

**Comment by seema84** [comment]
can confirm

**Comment by klugemonkey** [comment]
Tested crafting table with a banner and 3 dye (base banner), and the ingredients are returned after any action on the inventory after moving the output slot item to the inventory.  So, same problem with banner crafting.

**Comment by klugemonkey** [comment]
Tested color on leather boots, same problem.

**Comment by md-5** [comment]
```	at net.minecraft.server.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:34) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at net.minecraft.server.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:13) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at org.bukkit.craftbukkit.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:120) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at net.minecraft.server.PlayerConnection.a(PlayerConnection.java:1825) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at net.minecraft.server.PacketPlayInWindowClick.a(SourceFile:33) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at net.minecraft.server.PacketPlayInWindowClick.a(SourceFile:10) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at net.minecraft.server.PlayerConnectionUtils$1.run(SourceFile:13) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
	at net.minecraft.server.SystemUtils.a(SourceFile:137) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	... 5 more```
