### ISSUE TITLE
Bed Spawn location causing errors

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#306]
```[21:32:30] [Server thread/WARN]: java.lang.Exception
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.Chunk.a(Chunk.java:697)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.Chunk.a(Chunk.java:675)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:434)
[21:32:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:42)
[21:32:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14)
[21:32:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[21:32:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[21:32:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:151)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:134)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:130)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.World.getChunkAt(World.java:299)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.World.getChunkAtWorldCoords(World.java:295)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.World.getType(World.java:747)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.EntityHuman.getBed(EntityHuman.java:1337)
[21:32:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.entity.CraftPlayer.getBedSpawnLocation(CraftPlayer.java:923)
[21:32:30] [Server thread/WARN]: 	at com.earth2me.essentials.EssentialsPlayerListener.updateCompass(EssentialsPlayerListener.java:367)
[21:32:30] [Server thread/WARN]: 	at com.earth2me.essentials.EssentialsPlayerListener.access$100(EssentialsPlayerListener.java:35)
[21:32:30] [Server thread/WARN]: 	at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:275)
[21:32:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
[21:32:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:725)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.DedicatedServer.w(DedicatedServer.java:381)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:686)
[21:32:30] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:591)
```

**Comment by md-5** [comment]
I think this has resulted in some world corruption

```Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.block.CraftBed.load(CraftBed.java:27) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at org.bukkit.craftbukkit.block.CraftBed.load(CraftBed.java:11) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at org.bukkit.craftbukkit.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:27) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at org.bukkit.craftbukkit.block.CraftBed.<init>(CraftBed.java:16) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at org.bukkit.craftbukkit.block.CraftBlock.getState(CraftBlock.java:372) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at com.Acrobot.Breeze.Utils.BlockUtil.isChest(BlockUtil.java:35) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Player.PlayerInteract.onInteract(PlayerInteract.java:56) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit.jar:git-Bukkit-4bd524f]
```

**Comment by md-5** [comment]
Fixed what I think is the underlying bug.

Not sure why it caused map corruption though, but it should be able to recover.
