### ISSUE TITLE
Issues with recipes

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#307]
Unsure how to reproduce:

```Caused by: java.lang.NullPointerException
	at net.minecraft.server.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:34) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at net.minecraft.server.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:13) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at org.bukkit.craftbukkit.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:120) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at net.minecraft.server.PlayerConnection.a(PlayerConnection.java:1825) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at net.minecraft.server.PacketPlayInWindowClick.a(SourceFile:33) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at net.minecraft.server.PacketPlayInWindowClick.a(SourceFile:10) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at net.minecraft.server.PlayerConnectionUtils$1.run(SourceFile:13) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
	at net.minecraft.server.SystemUtils.a(SourceFile:137) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	... 5 more
```

**Comment by md-5** [comment]
#301
