### ISSUE TITLE
ChestShop not getting specific MaterialData at some point

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#309]
```Caused by: java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Attachable
	at com.Acrobot.Breeze.Utils.BlockUtil.getAttachedBlock(BlockUtil.java:55) ~[?:?]
	at com.Acrobot.ChestShop.Listeners.Block.Break.SignBreak.onSign(SignBreak.java:50) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit.jar:git-Bukkit-4bd524f]
	... 21 more
```

**Comment by md-5** [comment]
Should be solved
