### ISSUE TITLE
Selecting an effect in a beacon crashes the server

### ISSUE THREAD

**Issue by TNTUP** [SpigotMC/SpigotCraft#312]
I have attempted to build a beacon and enabling an effect of choice, like Haste I then I pick a diamond then clicking to the green circle and bam the server crashes.

On IRC pokechu replied with this "Ah, might be an issue with the plugin message/potion effect IDs, who knows" so I don't think I need to explain how to reproduce it to prevent crash abuse.

**Comment by md-5** [comment]
```[03:25:04] [Server thread/ERROR]: Exception stopping the server
net.minecraft.server.ReportedException: Ticking player
	at net.minecraft.server.EntityPlayer.playerTick(EntityPlayer.java:400) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.PlayerList.disconnect(PlayerList.java:388) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.PlayerConnection.a(PlayerConnection.java:1088) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.PlayerConnection.disconnect(PlayerConnection.java:260) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.PlayerList.u(PlayerList.java:1278) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:501) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:623) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.MobEffect.tick(SourceFile:106) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.EntityLiving.tickPotionEffects(EntityLiving.java:548) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.EntityLiving.W(EntityLiving.java:296) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.Entity.H_(Entity.java:305) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.EntityLiving.H_(EntityLiving.java:1858) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.EntityHuman.H_(EntityHuman.java:150) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.EntityPlayer.playerTick(EntityPlayer.java:319) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
```
