### ISSUE TITLE
Help Error {Vanilla?}

### ISSUE THREAD

**Issue by md-5** [SpigotMC/SpigotCraft#313]
```[04:08:15] [Server thread/ERROR]: Couldn't execute command for TNTUP: minecraft:help give
java.util.NoSuchElementException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721) ~[?:1.8.0_141]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742) ~[?:1.8.0_141]
	at com.google.common.collect.Iterators.getLast(Iterators.java:829) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at com.google.common.collect.Iterables.getLast(Iterables.java:848) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.CommandHelp.a(SourceFile:29) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:119) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:76) ~[craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.CommandDispatcher.a(CommandDispatcher.java:106) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.PlayerConnection.handleCommand(PlayerConnection.java:1358) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.PlayerConnection.a(PlayerConnection.java:1218) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.PacketPlayInChat.a(SourceFile:37) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.PacketPlayInChat.a(SourceFile:9) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
	at net.minecraft.server.SystemUtils.a(SourceFile:137) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:731) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.DedicatedServer.w(DedicatedServer.java:381) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:686) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:591) [craftbukkit-17w49b-R0.1-SNAPSHOT.jar:git-Bukkit-f15b7db]
```

**Comment by Pokechu22** [comment]
https://bugs.mojang.com/browse/MC-121661 (message appears when there isn't a command, but it should work for known commands)

**Comment by Pluginsel** [comment]
This is fixed in 18w19a;
[MC-121661](https://bugs.mojang.com/browse/MC-121661) - Typing /help + unavailable command returns "unexpected error" message

**Comment by Pluginsel** [comment]
@MD-5, This is fixed in 18w19a.
