### ISSUE TITLE
Essentials using /spawn or /setspawn makes server stop responding.

### ISSUE THREAD

**Issue by kjonte123** [SpigotMC/SpigotCraft#389]
Version 1.12.2

Everything has been working fine until today when my friend tried to go to spawn using /spawn and it made the server crash. I also tried to restart the server and set a new spawn, but using /setspawn made it crash aswell.

**I posted the logs in a .gz file **

Here's some crash/warning logs I found in the console: 

[2018-03-20-2.log.gz](https://github.com/SpigotMC/SpigotCraft/files/1830254/2018-03-20-2.log.gz)
[16:57:23 WARN]: [Essentials] Plugin Essentials v2.0.1-b482 generated an exception while executing task 39
org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for tag:yaml.org,2002:com.earth2me.essentials.settings.Spawns; exception=java.lang.NoSuchFieldException: typeDefinitions
 in 'reader', line 1, column 1:
    spawns:
    ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:313) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:467) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:41) ~[?:?]
        at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:33) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: org.yaml.snakeyaml.error.YAMLException: java.lang.NoSuchFieldException: typeDefinitions
        at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.constructJavaBean2ndStep(BukkitConstructor.java:231) ~[?:?]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:217) ~[?:?]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        ... 13 more
Caused by: java.lang.NoSuchFieldException: typeDefinitions
        at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_161]
        at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.constructJavaBean2ndStep(BukkitConstructor.java:224) ~[?:?]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:217) ~[?:?]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308) ~[craftbukkit.jar:git-Spigot-4bd94dc-bacaf92]
        ... 13 more

**Comment by md-5** [comment]
Update your essentials, also nothing to do with this server.
