### ISSUE TITLE
NPE on build

### ISSUE THREAD

**Issue by SlimeDog** [SpigotMC/SpigotCraft#420]
Spigot 1.13.1 b1861

java -jar BuildTools.jar --rev 1.13.1
Loading BuildTools version: git-BuildTools-566b920-77 (#77)
git version 1.8.3.1

NPE generated by build. spigot.jar still builds correctly (in the sense that it executes).
```
ERROR: Method a (Lcom/mojang/datafixers/Dynamic;)V couldn't be written.
java.lang.NullPointerException
        at org.jetbrains.java.decompiler.modules.decompiler.exps.AssignmentExprent.toJava(AssignmentExprent.java:122)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.listToJava(ExprProcessor.java:833)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.BasicBlockStatement.toJava(BasicBlockStatement.java:72)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:39)
        at org.jetbrains.java.decompiler.main.ClassWriter.methodLambdaToJava(ClassWriter.java:567)
        at org.jetbrains.java.decompiler.main.ClassWriter.classLambdaToJava(ClassWriter.java:157)
        at org.jetbrains.java.decompiler.modules.decompiler.exps.NewExprent.toJava(NewExprent.java:268)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.getCastedExprent(ExprProcessor.java:916)
        at org.jetbrains.java.decompiler.modules.decompiler.exps.InvocationExprent.toJava(InvocationExprent.java:335)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.listToJava(ExprProcessor.java:833)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.BasicBlockStatement.toJava(BasicBlockStatement.java:72)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:39)
        at org.jetbrains.java.decompiler.main.ClassWriter.methodLambdaToJava(ClassWriter.java:567)
        at org.jetbrains.java.decompiler.main.ClassWriter.classLambdaToJava(ClassWriter.java:157)
        at org.jetbrains.java.decompiler.modules.decompiler.exps.NewExprent.toJava(NewExprent.java:268)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.getCastedExprent(ExprProcessor.java:916)
        at org.jetbrains.java.decompiler.modules.decompiler.exps.InvocationExprent.toJava(InvocationExprent.java:335)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.listToJava(ExprProcessor.java:833)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.BasicBlockStatement.toJava(BasicBlockStatement.java:72)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.jmpWrapper(ExprProcessor.java:765)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.SequenceStatement.toJava(SequenceStatement.java:131)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:39)
        at org.jetbrains.java.decompiler.main.ClassWriter.methodToJava(ClassWriter.java:853)
        at org.jetbrains.java.decompiler.main.ClassWriter.classToJava(ClassWriter.java:265)
        at org.jetbrains.java.decompiler.main.ClassWriter.classToJava(ClassWriter.java:289)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:259)
        at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:87)
        at org.jetbrains.java.decompiler.struct.ContextUnit.save(ContextUnit.java:113)
        at org.jetbrains.java.decompiler.struct.StructContext.saveContext(StructContext.java:72)
        at org.jetbrains.java.decompiler.main.Fernflower.decompileContext(Fernflower.java:54)
        at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.decompileContext(ConsoleDecompiler.java:125)
        at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.main(ConsoleDecompiler.java:97)
```

**Comment by md-5** [comment]
This is the SpigotCraft bug tracker, and that error doesn't matter
