### ISSUE TITLE
Putting an item in an anvil crashes the client

### ISSUE THREAD

**Issue by Black-Hole** [SpigotMC/SpigotCraft#463]
- [ ] Bug exists on current Vanilla snapshot
- [X] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.13.2)
- [X] Bug does not exist on current Spigot version (1.13.2, 1.14.4)

java.lang.StackOverflowError: Unexpected error
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at jt.b(SourceFile:138)
	at bek.b(SourceFile:248)
	at bek.<init>(SourceFile:121)
	at bek.i(SourceFile:337)
	at bak.c(SourceFile:126)
	at bam.e(SourceFile:361)
	at bam.a(SourceFile:438)
	at dgv.a(SourceFile:118)
	at dgv$$Lambda$2622/98474301.accept(Unknown Source)
	at dda.d(SourceFile:153)
	at dda.e(SourceFile:263)
	at dda.e(SourceFile:275)
	at dda.a(SourceFile:96)
	at dgv.a(SourceFile:156)
	at bak.c(SourceFile:129)
	at bam.e(SourceFile:361)
	at bam.a(SourceFile:438)
	at dgv.a(SourceFile:118)
	at dgv$$Lambda$2622/98474301.accept(Unknown Source)
	at dda.d(SourceFile:153)
	at dda.e(SourceFile:263)
	at dda.e(SourceFile:275)
	at dda.a(SourceFile:96)
	at dgv.a(SourceFile:156)
	at bak.c(SourceFile:129)
	at bam.e(SourceFile:361)
	at bam.a(SourceFile:438)
	at dgv.a(SourceFile:118)
	at dgv$$Lambda$2622/98474301.accept(Unknown Source)
	at dda.d(SourceFile:153)
	at dda.e(SourceFile:263)
	at dda.e(SourceFile:275)
	at dda.a(SourceFile:96)
	at dgv.a(SourceFile:156)
	at bak.c(SourceFile:129)
	at bam.e(SourceFile:361)
	at bam.a(SourceFile:438)
	at dgv.a(SourceFile:118)
	at dgv$$Lambda$2622/98474301.accept(Unknown Source)
...

**Comment by MiniDigger** [comment]
https://streamable.com/hjiwb

**Comment by MiniDigger** [comment]
only seems to be happening to non damaged tools/weapons

**Comment by md-5** [comment]
yeah I can confirm this..... Vanilla is unaffected

**Comment by md-5** [comment]
Ok finally, looks solved to me

**Comment by Black-Hole** [comment]
I was not able to crash my client using an anvil anymore. I tested with some tools and renamed them.
