### ISSUE TITLE
Unknown target reason : java.lang.Exception: null

### ISSUE THREAD

**Issue by Blueeyestar** [SpigotMC/SpigotCraft#509]
CraftBukkit version git-Spigot-6f4ff1b-983305b (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

> [23:38:32] [Server thread/WARN]: Unknown target reason, please report on the issue tracker
java.lang.Exception: null
at net.minecraft.server.v1_16_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:175) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.EntityInsentient.setGoalTarget(EntityInsentient.java:165) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.BlockBeehive.b(SourceFile:106) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.BlockBeehive.a(SourceFile:91) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:367) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:268) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:238) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1224) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by md-5** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5866
